version: '3.10'

services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres-database
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: my_database
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:7.4.7-alpine3.21
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insights:
    image: redislabs/redisinsight:latest
    container_name: redis-insights
    ports:
      - "5540:5540"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.29.4-alpine3.23-slim
    container_name: nginx
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./test-static-folder:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  database-storage:
  redis_data: